version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: 3001
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      MONGO_NAME: ${MONGO_NAME}
    dns:
      - 8.8.8.8
      - 8.8.4.4